### ISSUE TITLE
Setting up Camera and I2C in the config

### ISSUE THREAD

**Issue by GordonGitSmith** [pimoroni/PanTiltFacetracker#4]
There is no comment in the instructions about setting up the camera or I2C in the configuration on the Pi. As is generally known the Camera needs to be 'activated' in the config. The Camera I set up just fine. But do I need to set up the I2C as well? I will try tomorrow as when I ran the Pi today only the tilt worked. I am guessing that without the I2C set up only one device (the tilt) is grabbing the code. I am sure that 'pan' is a functioning motor, as when the power is applied to the pi the 'pan' servo 'nudges' a couple of steps, so it can move. Do the instructions need to add a reminder to add both of these or is it just the Camera?

**Comment by Gadgetoid** [comment]
Is this using PanTilt HAT?

**Comment by GordonGitSmith** [comment]
Indeed

**Comment by Gadgetoid** [comment]
The PanTilt HAT one-line-installer should enable i2c automagically. I'll expand the guide with install details for PanTilt HAT and instructions for enabling the camera.

**Comment by GordonGitSmith** [comment]
My thanks. I will also try a new install on the sim card.
